### ISSUE TITLE
Is OMS a new license

### ISSUE THREAD

**Issue by ugintl** [Karaka-Management/Karaka#112]
Is OMS a new license?

**Comment by spl1nes** [comment]
Yes, you can create your own license as well. 

Github just supplies developers with some default licenses but nothing prevents you from creating your own license. In fact many commercial software solutions have their own license.

**Comment by ugintl** [comment]
@spl1nes So what does it allow and what does not? Does it give me liberty similar to MIT?

**Comment by spl1nes** [comment]
To summarize at the moment it doesn't allow you to do anything. In the future you will have to purchase the software (once it is finished) to use it. It is very far away from the MIT license, so no it doesn't give you similar liberty to the MIT license.

**Comment by ugintl** [comment]
understood
